### ISSUE TITLE
单独引用vendor.styl这个文件，display flex 失效

### ISSUE THREAD

**Issue by q134678123** [jaywcjlove/AutoPrefixCSS#2]
用的flex:1,
结果生成以下   
 -webkit-box-flex: 0;
    -moz-box-flex: 0;
    width: 1;
    -webkit-flex: 0 0 auto;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
浏览器表示毫无兴趣（Chorme）

**Comment by jaywcjlove** [comment]
@q134678123 请使用 [Autoprefixer](https://github.com/postcss/autoprefixer)，此仓库已经不在维护了。
